### PR TITLE
Added support for parallel code and general switch/switch_single

### PR DESCRIPTION
**Pull request by dfok**
Hi Yori,

I've been using your oxdoc code for quite some time. I finally decided to contribute my minor edits to the code to allow for parallel Ox code and more general switch statements. Perhaps you are no longer using oxdoc (or Ox itself), but perhaps you want to pull my code.

Best, Dennis
PS. This is also my first attempt at open source contribution through github

### CODE REVIEW

**Comment by yozw** [comment]
Hi Dennis -- sorry for the late reply; I hadn't noticed the email, as it went into a separate folder and I'm not used to getting pull requests :) I'll have a look this weekend.

**Comment by yozw** [comment]
One thing that would be good to add is a few tests, in particular in ParserTest.java.

**Comment by dfok** [comment]
I have added these tests.. (earlier I had some problems compiling the unit tests). Previous code does not pass these tests, new code (of course) does.

**Comment by yozw** [comment]
Great. Many thanks for this, and also for fixing the trailing spaces.

**Comment by dfok** [comment]
My pleasure...

**Pull request merged**
